import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Truffle Mushroom Bruschetta',
    description: 'Toasted artisan sourdough topped with wild mushrooms, truffle oil, and shaved parmesan.',
    price: 450,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&w=600&q=80',
    isVegetarian: true,
  },
  {
    id: '2',
    name: 'Spicy Prawn Tempura',
    description: 'Crispy fried prawns tossed in a spicy dynamite sauce with sesame seeds.',
    price: 650,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?auto=format&fit=crop&w=600&q=80',
    isSpicy: true,
  },
  {
    id: '3',
    name: 'Grilled Salmon Fillet',
    description: 'Pan-seared salmon served with asparagus, mashed potatoes, and lemon butter sauce.',
    price: 1200,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '4',
    name: 'Herb Crusted Lamb Rack',
    description: 'Succulent lamb rack with a herb crust, served with roasted root vegetables and red wine jus.',
    price: 1500,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1544516423-c8b290ae5589?auto=format&fit=crop&w=600&q=80',
    isChefChoice: true,
  },
  {
    id: '5',
    name: 'Wild Risotto Verde',
    description: 'Creamy arborio rice cooked with spinach, peas, asparagus, and finished with mascarpone.',
    price: 950,
    category: 'Main Course',
    image: 'https://images.unsplash.com/photo-1633966887768-64f9a867bd0b?auto=format&fit=crop&w=600&q=80',
    isVegetarian: true,
  },
  {
    id: '6',
    name: 'Belgian Chocolate Fondant',
    description: 'Warm chocolate lava cake served with a scoop of Madagascar vanilla bean ice cream.',
    price: 400,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=600&q=80',
    isVegetarian: true,
    isChefChoice: true,
  },
  {
    id: '7',
    name: 'Saffron Pistachio Kunafa',
    description: 'Traditional middle-eastern dessert with crispy pastry, sweet cheese, and saffron syrup.',
    price: 550,
    category: 'Desserts',
    image: 'https://images.unsplash.com/photo-1576458088443-04a19bb13da6?auto=format&fit=crop&w=600&q=80',
    isVegetarian: true,
  },
  {
    id: '8',
    name: 'Signature Gold Mojito',
    description: 'A premium twist on the classic with gold dust, premium white rum, mint, and lime.',
    price: 450,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    isChefChoice: true,
  },
  {
    id: '9',
    name: 'Vintage Red Wine (Glass)',
    description: 'A selection of our finest house red wines aged to perfection.',
    price: 700,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: '10',
    name: 'Truffle Parmesan Fries',
    description: 'Crispy golden fries tossed with truffle oil and parmesan dust.',
    price: 250,
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1573080496987-a199f8cd4058?auto=format&fit=crop&w=600&q=80',
    tags: ['Add-on'],
    isVegetarian: true,
  },
];